FROM docker.io/continuumio/miniconda3

# Set working directory
WORKDIR /app

# Copy the environment file
COPY ml_tuning_env.yml .

# Create Conda environment
RUN conda env create -f ml_tuning_env.yml && \
    conda clean --all --yes && \
    rm -rf /opt/conda/pkgs/*

# Make RUN commands use the new environment
SHELL ["conda", "run", "-n", "ml_tuning_env", "/bin/bash", "-c"]

# Default command to run when starting the container
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "ml_tuning_env"]
CMD ["python", "tuning_ml_models.py"]